const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const slice=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b));
for(const m of source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
const storage={},records={a:{correct:1,last:'correct'},b:{wrong:1,last:'wrong'},c:{correct:2,last:'correct'},d:{wrong:1,last:'wrong'},fresh:{correct:0,wrong:0}};
const plan={items:{a:{due:'2026-10-01'},b:{due:'2026-10-01'},c:{due:'2026-11-01'},d:{due:'2026-11-01'},fresh:{due:'2026-09-01'}}};
const ctx={Date,Object,Math,Number,planFor:()=>plan,dateKey:()=> '2026-10-01',planQuestions:()=>['fresh','a','b','c','d','unseen'].map(uid=>({uid})),qkey:q=>q.uid,planRecord:uid=>records[uid],planBookForUid:uid=>['a','b'].includes(uid)?'book1':'book2',safeGet:k=>storage[k],safeSet:(k,v)=>storage[k]=JSON.parse(JSON.stringify(v)),safeRemove:k=>delete storage[k],cloudSyncSoon(){},el:()=>({classList:{remove(){}}}),toast(){},renderQuestion(){},savedExtraSessionForToday(){},byUid:uid=>({uid}),renderHome(){}};
vm.createContext(ctx);
vm.runInContext(`let session=null,activeBook='book1';const STORE_SES_PREFIX='test_';${slice('const sessionStoreKey=', 'function savedExtraSessionForToday(')}${slice('function routeReviewUids(', 'function resolveQuestions(')}${slice('function resumeSession(', '/* ============ 問題描画')}${slice('function localSessionPayload(', 'function progressBackupData(')}`,ctx);
assert.deepEqual(Array.from(ctx.routeReviewUids()),['b','a','d','c']);
storage['test_shared-plan']={mode:'plan',uids:['fresh'],idx:0};
storage['test_book1']={mode:'order',uids:['fresh'],idx:0};
const planBefore=JSON.stringify(plan),requiredBefore=JSON.stringify(storage.test_shared-plan);
ctx.startRouteReview();
assert.equal(storage['test_route-review'].mode,'routeReview');
assert.deepEqual(storage['test_route-review'].uids,['b','a','d','c']);
assert.equal(storage.test_book1.mode,'order');
assert.equal(JSON.stringify(storage.test_shared-plan),requiredBefore);
assert.equal(JSON.stringify(plan),planBefore);
vm.runInContext("session.idx=0;session.resumeIdx=1;activeBook='book2';saveSession();session=null;",ctx);
ctx.startRouteReview();
assert.equal(vm.runInContext('session.idx',ctx),1);
assert.equal(vm.runInContext('session.uids[session.idx]',ctx),'a');
assert.equal(ctx.localSessionPayload()['route-review'].resumeIdx,1);
assert.equal(ctx.mergeSessionPayload({}, {'route-review':{updatedAt:5,idx:2}})['route-review'].idx,2);
assert.equal(ctx.mergeSessionPayload({'route-review':{updatedAt:6,deleted:true}}, {'route-review':{updatedAt:5,idx:2}})['route-review'].deleted,true);
vm.runInContext('clearSession()',ctx);
assert.equal(storage['test_route-review'],undefined);
assert.equal(JSON.stringify(storage.test_shared-plan),requiredBefore);
for(const key of Object.keys(records))delete records[key];
assert.equal(ctx.routeReviewUids().length,0);
ctx.startRouteReview();assert.equal(storage['test_route-review'],undefined);
console.log('PASS: review-only selection, due/wrong priority, both books, independent save/resume, cloud merge/tombstone, empty state and syntax');
